### ISSUE TITLE
No objects to concatenate

### ISSUE THREAD

**Issue by MKalloub** [MuenchnerWeisswurst/BLOND-CONVERTER#1]
Hi Muenchner,

Thank you for your code, it helped me so much.
But I faced the following error, how to solve it?:

`Traceback (most recent call last):
  File "convert_sum.py", line 126, in <module>
    frames = get_clear_data()
  File "convert_sum.py", line 87, in get_clear_data
    frames_array[i] = pd.concat(frames_array[i])
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/concat.py", line 228, in concat
    copy=copy, sort=sort)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/concat.py", line 262, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
Closing remaining open files:../data/converted_sum.hdf5...done`

**Comment by MKalloub** [comment]
Hi,
I solved the issue, it was in downloading dataset
When download dataset, medals data located at folder BLOND-CONVERTER/BLOND/BLOND-250
whereas summary files "clear folders" located in different path.

So, you have 2 solution:
1- edit download code and place all data in the same folder.
or
2- after downloading data just copy-paste summary files to BLOND-CONVERTER/BLOND/BLOND-250

then start conversion

Regards,

**Comment by LucasBFrancois** [comment]
Line 40 add: `BLOND-CONVERTER/` in front of `BLOND/BLOND-250/` to solve that issue, so it becomes:
`directory = 'BLOND-CONVERTER/BLOND/BLOND-250/'+date+clear`
